### ISSUE TITLE
How to edit pg w/ Recording of Open Space + gitbook not synched to github code?

### ISSUE THREAD

**Issue by coopchange** [microsolidarity/handbook#2]
This https://github.com/microsolidarity/handbook/tree/master/discussing
not the same as
this https://www.microsolidarity.cc/discussing

which I discovered as I was trying to make a PR for changing the link associated with the Peer Incubator to the following, [tiny.cc/PeerIncubator](http://tiny.cc/PeerIncubator) (Rich, if you could be sweetheart and just go ahead and make that change, it'd be much appreciated, thanks!)

**Comment by rdbartlett** [comment]
hmmmmm ok I need to investigate the sync between github and gitbook. one moment please...

**Comment by rdbartlett** [comment]
Ok I think I fixed it - can you make an edit in Github to confirm it is working for you?

**Comment by rdbartlett** [comment]
PR #4 works as expected so I believe the sync is working now
